name: Build and Run Docker Image

on:
  pull_request:
    branches:
      - "CI_Release_Development"   # Trigger on PR closed for specific branch
    types: 
      - closed # Only trigger when PR is closed (merged)

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  # Ensure PR is merged before continuing

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for building images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker (if needed for pushing, but skipped in your case)
      # If you were pushing the image to a registry, you would log in here.
      # - name: Docker Login
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ secrets.HOST }}  # Optional for non-registry use

      # Step 4: Build Docker image using the provided Dockerfile
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile 
          tags: myapp:latest  
          push: false  

      # Step 5: Run the Docker image as a container
      - name: Run Docker container
        run: |
          docker run -d -p 80:80 myapp:latest
      

